
package org.openmrs.module.isanteplus.configuration.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "BioPluginServiceV8", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.2.109.176/M2SYS.BioPluginWeb/BioPluginServiceV8.asmx?wsdl")
public class BioPluginServiceV8 extends Service {

    private final static URL BIOPLUGINSERVICEV8_WSDL_LOCATION;
    private final static WebServiceException BIOPLUGINSERVICEV8_EXCEPTION;
    private final static QName BIOPLUGINSERVICEV8_QNAME = new QName("http://tempuri.org/", "BioPluginServiceV8");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.2.109.176/M2SYS.BioPluginWeb/BioPluginServiceV8.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIOPLUGINSERVICEV8_WSDL_LOCATION = url;
        BIOPLUGINSERVICEV8_EXCEPTION = e;
    }

    public BioPluginServiceV8() {
        super(__getWsdlLocation(), BIOPLUGINSERVICEV8_QNAME);
    }

    public BioPluginServiceV8(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIOPLUGINSERVICEV8_QNAME, features);
    }

    public BioPluginServiceV8(URL wsdlLocation) {
        super(wsdlLocation, BIOPLUGINSERVICEV8_QNAME);
    }

    public BioPluginServiceV8(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIOPLUGINSERVICEV8_QNAME, features);
    }

    public BioPluginServiceV8(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BioPluginServiceV8(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns BioPluginServiceV8Soap
     */
    @WebEndpoint(name = "BioPluginServiceV8Soap")
    public BioPluginServiceV8Soap getBioPluginServiceV8Soap() {
        return super.getPort(new QName("http://tempuri.org/", "BioPluginServiceV8Soap"), BioPluginServiceV8Soap.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BioPluginServiceV8Soap
     */
    @WebEndpoint(name = "BioPluginServiceV8Soap")
    public BioPluginServiceV8Soap getBioPluginServiceV8Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BioPluginServiceV8Soap"), BioPluginServiceV8Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIOPLUGINSERVICEV8_EXCEPTION != null) {
            throw BIOPLUGINSERVICEV8_EXCEPTION;
        }
        return BIOPLUGINSERVICEV8_WSDL_LOCATION;
    }

}
