
package org.openmrs.module.isanteplus.configuration.wsdl;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BioPluginServiceV8Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BioPluginServiceV8Soap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInfo", action = "http://tempuri.org/GetInfo")
    @WebResult(name = "GetInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInfo", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.GetInfo")
    @ResponseWrapper(localName = "GetInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.GetInfoResponse")
    public String getInfo();

    /**
     * 
     * @param locationID
     * @param biometricXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Identify", action = "http://tempuri.org/Identify")
    @WebResult(name = "IdentifyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Identify", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.Identify")
    @ResponseWrapper(localName = "IdentifyResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.IdentifyResponse")
    public String identify(
        @WebParam(name = "BiometricXml", targetNamespace = "http://tempuri.org/")
        String biometricXml,
        @WebParam(name = "LocationID", targetNamespace = "http://tempuri.org/")
        int locationID);

    /**
     * 
     * @param locationID
     * @param id
     * @param biometricXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Verify", action = "http://tempuri.org/Verify")
    @WebResult(name = "VerifyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Verify", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.Verify")
    @ResponseWrapper(localName = "VerifyResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.VerifyResponse")
    public String verify(
        @WebParam(name = "BiometricXml", targetNamespace = "http://tempuri.org/")
        String biometricXml,
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "LocationID", targetNamespace = "http://tempuri.org/")
        int locationID);

    /**
     * 
     * @param template2
     * @param template1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VerifyTemplate", action = "http://tempuri.org/VerifyTemplate")
    @WebResult(name = "VerifyTemplateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VerifyTemplate", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.VerifyTemplate")
    @ResponseWrapper(localName = "VerifyTemplateResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.VerifyTemplateResponse")
    public String verifyTemplate(
        @WebParam(name = "Template1", targetNamespace = "http://tempuri.org/")
        String template1,
        @WebParam(name = "Template2", targetNamespace = "http://tempuri.org/")
        String template2);

    /**
     * 
     * @param locationID
     * @param id
     * @param biometricXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/Register")
    @WebResult(name = "RegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.RegisterResponse")
    public String register(
        @WebParam(name = "BiometricXml", targetNamespace = "http://tempuri.org/")
        String biometricXml,
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "LocationID", targetNamespace = "http://tempuri.org/")
        int locationID);

    /**
     * 
     * @param locationID
     * @param id
     * @param biometricXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Update", action = "http://tempuri.org/Update")
    @WebResult(name = "UpdateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Update", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.UpdateResponse")
    public String update(
        @WebParam(name = "BiometricXml", targetNamespace = "http://tempuri.org/")
        String biometricXml,
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "LocationID", targetNamespace = "http://tempuri.org/")
        int locationID);

    /**
     * 
     * @param id
     * @param engineName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteID", action = "http://tempuri.org/DeleteID")
    @WebResult(name = "DeleteIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteID", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.DeleteID")
    @ResponseWrapper(localName = "DeleteIDResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.DeleteIDResponse")
    public String deleteID(
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "engineName", targetNamespace = "http://tempuri.org/")
        String engineName);

    /**
     * 
     * @param newID
     * @param oldID
     * @param engineName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeID", action = "http://tempuri.org/ChangeID")
    @WebResult(name = "ChangeIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangeID", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.ChangeID")
    @ResponseWrapper(localName = "ChangeIDResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.ChangeIDResponse")
    public String changeID(
        @WebParam(name = "Old_ID", targetNamespace = "http://tempuri.org/")
        String oldID,
        @WebParam(name = "New_ID", targetNamespace = "http://tempuri.org/")
        String newID,
        @WebParam(name = "engineName", targetNamespace = "http://tempuri.org/")
        String engineName);

    /**
     * 
     * @param id
     * @param engineName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IsRegistered", action = "http://tempuri.org/IsRegistered")
    @WebResult(name = "IsRegisteredResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsRegistered", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.IsRegistered")
    @ResponseWrapper(localName = "IsRegisteredResponse", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.IsRegisteredResponse")
    public String isRegistered(
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "engineName", targetNamespace = "http://tempuri.org/")
        String engineName);

    /**
     * 
     * @param locationID
     * @param id
     * @param biometricXml
     */
    @WebMethod(operationName = "AddToCache", action = "http://tempuri.org/AddToCache")
    @Oneway
    @RequestWrapper(localName = "AddToCache", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.AddToCache")
    public void addToCache(
        @WebParam(name = "BiometricXml", targetNamespace = "http://tempuri.org/")
        String biometricXml,
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "LocationID", targetNamespace = "http://tempuri.org/")
        int locationID);

    /**
     * 
     * @param locationID
     * @param id
     * @param biometricXml
     */
    @WebMethod(operationName = "UpdateToCache", action = "http://tempuri.org/UpdateToCache")
    @Oneway
    @RequestWrapper(localName = "UpdateToCache", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.UpdateToCache")
    public void updateToCache(
        @WebParam(name = "BiometricXml", targetNamespace = "http://tempuri.org/")
        String biometricXml,
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "LocationID", targetNamespace = "http://tempuri.org/")
        int locationID);

    /**
     * 
     * @param id
     * @param engineName
     */
    @WebMethod(operationName = "DeleteFromCache", action = "http://tempuri.org/DeleteFromCache")
    @Oneway
    @RequestWrapper(localName = "DeleteFromCache", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.DeleteFromCache")
    public void deleteFromCache(
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "engineName", targetNamespace = "http://tempuri.org/")
        String engineName);

    /**
     * 
     * @param newID
     * @param oldID
     * @param engineName
     */
    @WebMethod(operationName = "ChangeIDToCache", action = "http://tempuri.org/ChangeIDToCache")
    @Oneway
    @RequestWrapper(localName = "ChangeIDToCache", targetNamespace = "http://tempuri.org/", className = "org.openmrs.module.isanteplus.configuration.wsdl.ChangeIDToCache")
    public void changeIDToCache(
        @WebParam(name = "Old_ID", targetNamespace = "http://tempuri.org/")
        String oldID,
        @WebParam(name = "New_ID", targetNamespace = "http://tempuri.org/")
        String newID,
        @WebParam(name = "engineName", targetNamespace = "http://tempuri.org/")
        String engineName);

}
